# Generated by Django 3.0.1 on 2021-01-13 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(default=101)),
                ('title', models.CharField(default='Item1', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('remaining_count', models.IntegerField(default=3)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('booking_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibsapp.Inventory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibsapp.Member')),
            ],
        ),
    ]
